name: FastAPI Deploy (No Docker)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set +e

            cd ~

            sudo rm -rf car_detection_api
            sudo rm -rf ~/.cache/pip
            sudo apt clean
            sudo apt autoremove -y

            git clone https://${{ secrets.GH_TOKEN }}@github.com/bhavuk1409/car_detection_api.git
            cd car_detection_api

            sudo apt update -y
            sudo apt install -y python3-pip python3-venv

            python3 -m venv venv
            source venv/bin/activate

            pip install --upgrade pip

            pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

            export CUDA_VISIBLE_DEVICES=""

            pip install -r requirements.txt --no-cache-dir

            echo "Stopping old server safely..."
            ps aux | grep uvicorn | grep -v grep | awk '{print $2}' | xargs -r sudo kill -9

            echo "Starting FastAPI..."
            nohup uvicorn api.main:app --host 0.0.0.0 --port 8000 > log.txt 2>&1 &

            sleep 5
            tail -n 50 log.txt || true
